services:
  aclservice:
    container_name: aclservice
    image: stjarnstoft/aclservice:dev
    build:
      context: ./AclService
      dockerfile: Dockerfile
      target: dev
    environment:
      GB_CONSTRING: "mongodb://acldb"
    ports:
      - "8093:8080"
    volumes:
      - ./AclService/:/app
  acldb:
    container_name: acldb
    image: mongo
    volumes:
      - acldbdata:/data/db
  guestbookservice:
    container_name: guestbookservice
    image: stjarnstoft/guestbookserviece:dev
    build:
      context: ./GuestbookService
      dockerfile: Dockerfile
      target: dev
    environment:
      GB_CONSTRING: "mongodb://guestbookdb"
    ports:
      - "8092:8080"
    volumes:
      - ./GuestbookService/:/app
  guestbookdb:
    container_name: guestbookdb
    image: mongo
    volumes:
      - guestbookdbdata:/data/db
  userservice:
    container_name: userservice
    image: stjarnstoft/userservice:dev
    build:
      context: ./UserService
      dockerfile: Dockerfile
      target: dev
    environment:
      GB_CONSTRING: "mongodb://userdb"
    ports:
      - "8091:8080"
    volumes:
      - ./UserService/:/app
  userdb:
    container_name: userdb
    image: mongo
    volumes:
      - userdbdata:/data/db
  apigateway:
    container_name: apigateway
    image: stjarnstoft/apigateway:dev
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
      target: dev
    environment:
      GUESTBOOK_ROOT_DOMAIN: "localhost:8080"
      GUESTBOOK_HOST: "guestbookservice:8080"
      USER_HOST: "userservice:8080"
      ACL_HOST: "aclservice:8080"
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./ApiGateway/:/app
  frontend:
    container_name: frontend
    image: stjarstoft/frontend:dev
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      GUESTBOOK_ROOT_DOMAIN: "localhost:8888"
      GATEWAY_HOST: "apigateway:8080"
    ports:
      - "8888:8080"
      - "2346:2345"
    volumes:
      - ./Frontend/:/app
volumes:
  acldbdata:
  guestbookdbdata:
  userdbdata:
